version: '3.8'

services:
  api:
    image: rodcordeiro/apprender:latest
    container_name: apprender_api
    restart: always
    ports:
      - '3333:80'
    
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      HOST: 0.0.0.0
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES: ${JWT_EXPIRES}

      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_NAME: ${DB_NAME}
    networks:
      - apprender
  db:
    image: mysql:latest
    container_name: apprender_db
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apprender_db
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
    networks:
      - apprender
    volumes:
      - apprender
    

networks:
  apprender:
    driver: bridge
